### ISSUE TITLE
flags missing in shex.jsonld

### ISSUE THREAD

**Issue by hsolbrig** [shexSpec/shexTest#15]
1literalPatterni fails json to rdf conversion.  shex.jsonld needs:

    "flags": {
      "@id": "shex:flags",
      "@language": null
    },

(or equivalent)

**Comment by gkellogg** [comment]
Updated in https://github.com/shexSpec/shexspec.github.io/commit/07d3e76be478d8c7f8c2e9d3b1f95635890239e0.

@ericprud will need to push the vocabulary files up to w3c.

**Comment by ericprud** [comment]
Done, note [encoding issues](https://github.com/shexSpec/shexspec.github.io/commit/a1a7bfa10fe71be2b4ee46ab6400b3e0f2f454ac) and [version skew](https://github.com/shexSpec/shexspec.github.io/issues/5).
