### ISSUE TITLE
1valExprRef-IV1_pass-lit-equal import trait not specified

### ISSUE THREAD

**Issue by hsolbrig** [shexSpec/shexTest#35]
Test `1valExprRef-IV1_pass-lit-equal` uses import, but `sht:Import` is not a trait

**Comment by hsolbrig** [comment]
`1valExprRefbnode-IV1_fail-lit-short` and `1valExprRefbnode-IV1_fail-lit-equal` are missing this as well -- basically anything with `IV1` in the name

**Comment by ericprud** [comment]
[fixed](https://github.com/shexSpec/shexTest/commit/967ac244cbed3296685bedf04dd217a87e45fd73)
